TEST_CFD_SOURCES= \
    test_cfd_abstracttx_controller.cpp \
    test_cfd_address.cpp \
    test_cfd_elements_address.cpp \
    test_cfd_fee.cpp \
    test_cfd_signparameter.cpp \
    test_cfd_confidentialtx_controller.cpp \
    test_cfd_confidentialtx_context.cpp \
    test_cfd_transaction_controller.cpp \
    test_cfd_transaction_context.cpp \
    test_cfd_coin_selection.cpp \
    test_cfd_utxoutil.cpp \
    test_cfdapi_ledger.cpp

TEST_CFD_STATIC_SOURCES= 

TEST_CFD_CAPI_SOURCES= \
    capi/test_cfdcapi_address.cpp \
    capi/test_cfdcapi_coin.cpp \
    capi/test_cfdcapi_common.cpp \
    capi/test_cfdcapi_elements_address.cpp \
    capi/test_cfdcapi_elements_transaction.cpp \
    capi/test_cfdcapi_key.cpp \
    capi/test_cfdcapi_ledger \
    capi/test_cfdcapi_script.cpp \
    capi/test_cfdcapi_transaction.cpp

