# ./include/cfd/Makefile.inc

CFD_ELEMENTS_PKGINCLUDE_FILES = \
  cfd_elements_address.h \
  cfd_elements_transaction.h \
  cfdapi_elements_address.h \
  cfdapi_elements_transaction.h \
  cfdapi_elements_pegin.h

CFD_PKGINCLUDE_FILES = \
  cfd_common.h \
  cfd_fee.h \
  cfd_transaction_common.h \
  cfd_transaction.h \
  cfd_address.h \
  cfd_utxo.h \
  cfdapi_transaction.h \
  cfdapi_address.h \
  cfdapi_hdwallet.h \
  cfdapi_key.h \
  cfdapi_coin.h \
  $(CFD_ELEMENTS_PKGINCLUDE_FILES)

