name: create-release-upload

on: 
  push:
    tags:
    - 'v*'

env:
  CMAKE_VERSION: 3.15.5

jobs:
  create-releases:
    name: create-releases
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
#      continue-on-error: true
    - name: write upload url
      env:
        url: ${{ steps.create_release.outputs.upload_url }}
      run: |
        echo $url > upload_url.txt
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact-upload_url
        path: upload_url.txt

  upload-object-windows-vs2019:
    name: upload-object-win-vs2019
    needs: create-releases
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: download artifact
      uses: actions/download-artifact@v1
      with:
        name: artifact-upload_url
    - name: dump upload url
      id: get_url
      run: |
        export up_url="$(cat artifact-upload_url/upload_url.txt)"
        echo "::set-output name=upload_url::$up_url"
        echo "url=$up_url"
      shell: bash
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash
    - name: dump version
      env:
        version: ${{ steps.get_version.outputs.VERSION }}
      run: echo "version=${version}"
      shell: bash
    - name: create folder
      run: mkdir dist
    - name: cmake-build
      id: cmake_build
      run: |
        cmake -S . -B build
        cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_SHARED=on -DENABLE_CAPI=on -DENABLE_TESTS=off -DENABLE_JS_WRAPPER=off --build build
        cmake --build build --parallel 2 --config Release
        cd ../..
      timeout-minutes: 20
    - name: cmake-install
      run: |
        cmake -DCMAKE_INSTALL_PREFIX="./dist" --install build
        cmake --install build
        cd dist
        del /F /Q cmake\wallycore-*
        del /F /Q lib\wallycore.*
        del /F /Q lib\libwallycore.*
        del /F /Q lib\pkgconfig\wallycore.pc
      shell: cmd
    - name: create archive file
      run: |
        cd dist
        Compress-Archive -Path ./* -DestinationPath ../cfd.zip
        cd ..
        echo "---- dump zip file ----"
        dir .
    - name: Upload Release Asset
      id: upload-release-asset 
#      if: success()
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_url.outputs.upload_url }}
        asset_path: ./cfd.zip
        asset_name: cfd-${{ steps.get_version.outputs.VERSION }}-win-vs2019-x86_64.zip
        asset_content_type: application/zip

  upload-object-ubuntu:
    name: upload-object-ubuntu
    needs: create-releases
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04]

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: cmake-useCache-ubuntu
      uses: actions/cache@v1
      id: cache
      with:
        path: cache/cmake
        key: ${{ runner.os }}-cmake-3.15.5-x64
        restore-keys: ${{ runner.os }}-cmake-3.15.5-x64
    - name: cmake-download-ubuntu
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p cache/cmake
        cd cache/cmake
        wget https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION-Linux-x86_64.tar.gz
        cd ../..
    - name: cmake-setting-ubuntu
      run: |
        export cmake_file_name="cmake-$CMAKE_VERSION-Linux-x86_64"
        cd cache/cmake
        tar zxvf $cmake_file_name.tar.gz
        chmod +x $cmake_file_name/bin/cmake $cmake_file_name/bin/ctest
        export CURRENT_DIR=$(pwd)
        echo ::add-path::$CURRENT_DIR/$cmake_file_name/bin
        cd ../..
    - name: cmake-build
      id: cmake_build
      run: |
        mkdir dist
        mkdir build
        cmake -S . -B build
        cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_SHARED=on -DENABLE_CAPI=on -DENABLE_TESTS=off -DENABLE_JS_WRAPPER=off -DTARGET_RPATH="/usr/local/lib" --build build
        cmake --build build --parallel 2 --config Release
        cd build
        sudo make install DESTDIR=../dist
        cd ..
    - name: create archive file
      run: |
        cd dist
        zip -r cfd.zip usr
        echo "---- dump zip file ----"
        ls -l
    - name: download artifact
      uses: actions/download-artifact@v1
      with:
        name: artifact-upload_url
    - name: dump upload url
      id: get_url
      run: |
        url=$(cat artifact-upload_url/upload_url.txt)
        echo ::set-output name=upload_url::$url
    - name: Upload Release Asset Ubuntu-18.04
      if: matrix.os == 'ubuntu-18.04'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_url.outputs.upload_url }}
        asset_path: ./dist/cfd.zip
        asset_name: cfd-${{ steps.get_version.outputs.VERSION }}-ubuntu1804-gcc-x86_64.zip
        asset_content_type: application/zip
    - name: Upload Release Asset Ubuntu-16.04
      if: matrix.os == 'ubuntu-16.04'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_url.outputs.upload_url }}
        asset_path: ./dist/cfd.zip
        asset_name: cfd-${{ steps.get_version.outputs.VERSION }}-ubuntu1604-gcc-x86_64.zip
        asset_content_type: application/zip
    - name: ubuntu-after
      run: rm -rf cache/cmake/cmake-$CMAKE_VERSION-Linux-x86_64

  upload-object-alpine:
    name: upload-object-alpine
    needs: create-releases
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: list
      run: ls -a $GITHUB_WORKSPACE
    - name: docker setup
      uses: docker://alpine:3.10
      with:
        entrypoint: /github/workspace/.github/workflows/docker/alpine_build_entrypoint.sh
    - name: create archive file
      run: |
        echo "---- dump output data ----"
        ls -l $GITHUB_WORKSPACE/dist/usr/local/*
        mkdir -p /tmp/cfd
        sudo chmod 777 /tmp/cfd
        sudo chown runner /tmp/cfd
        sudo cp -r $GITHUB_WORKSPACE/dist/usr /tmp/cfd
        cd /tmp/cfd
        sudo zip -r /tmp/cfd/cfd.zip usr
        sudo chmod 777 /tmp/cfd/cfd.zip
        sudo chown runner /tmp/cfd/cfd.zip
        sudo cp -rp /tmp/cfd/cfd.zip $GITHUB_WORKSPACE/dist/cfd.zip
        echo "---- dump zip file ----"
        sudo ls -l /tmp/cfd
    - name: download artifact
      uses: actions/download-artifact@v1
      with:
        name: artifact-upload_url
    - name: dump upload url
      id: get_url
      run: |
        url=$(cat artifact-upload_url/upload_url.txt)
        echo ::set-output name=upload_url::$url
    - name: Upload Release Asset
      id: upload-release-asset 
#      if: success()
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_url.outputs.upload_url }}
        asset_path: /tmp/cfd/cfd.zip
        asset_name: cfd-${{ steps.get_version.outputs.VERSION }}-alpine_x86_64.zip
        asset_content_type: application/zip
